apiVersion: mdcap.robin.io/v1
kind: FUNCTION
metadata:
  name: test10
spec:
  version: v1
  operator: shell
  cmd: ''
  source: functions/src/test10.sh
  description: test script for ROBINCLUSTER
  envs: ''
  etypes:
  - ROBINCLUSTER
  reserved_envs: UPDATE_PAYLOAD,ACCESS_TOKEN
  fanout: 1
  mode: 0
  action: mutable
