apiVersion: mdcap.robin.io/v1
kind: ROBINCLUSTER
metadata:
  name: sjc
  flavor: default
  version: '1.0'
  description: 3 node Robin CNP Cluster
  labels:
    location: sjc
spec:
  infraRef:
    - name: sjc001.robin.io
      kind: BM
    - name: sjc002.robin.io
      kind: BM
    - name: sjc003.robin.io
      kind: BM
  robin_config:
    build_url: http://10.9.200.61:8080/job/Robin_5.2.x_Binary/373/artifact/artifacts/
    server_install_args: "--ignore-warnings"
    agent_install_args: "--ignore-warnings"
    install_type: HA
    name: sjc
    primary_master: sjc001.robin.io
    secondary_masters:
    - sjc002.robin.io
    - sjc003.robin.io
    agents: []    
    robin_password: Passw0rd
    robin_user: admin
    version: 5.2.4-373
    vip: 10.10.1.45
    vrid: '222'
